apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: techtrends-python2.7
    tag: python2.7
  name: techtrends
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: techtrends-py-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: python-helloworld
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: IfNotPresent
        name: techtrends-app
        ports:
        - containerPort: {{ .Values.containerPort }}
        resources:
          requests:
            cpu: {{ .Values.resources.requests.CPU }}
            memory: {{ .Values.resources.requests.memory }}
          limits:
            cpu: {{ .Values.resources.limits.CPU }}
            memory: {{ .Values.resources.limits.memory }}
        livenessProbe:
		 httpGet:
		   path: {{ .Values.livenessProbe.path }}
		   port: 3111
	   readinessProbe:
	      path: {{ .Values.readinessProbe.path }}
	      port: 3111
