apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: techtrends
    name: techtrends
    namespace: sandbox
    resourceVersion: "6546"
    uid: 7c39673f-4012-4fe2-84f6-3f9c3fdbba58
  spec:
    clusterIP: 10.43.111.167
    clusterIPs:
    - 10.43.111.167
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: {{ .Values.service.port }]
      protocol: {{ .Values.service.protocol }}
      targetPort: {{ .Values.service.targetPort }}
    selector:
      app: techtrends
    sessionAffinity: None
    type: {{ .Values.service.ClusterIP }}
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""

