apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: techtrends-python2.7
    tag: python2.7
  name: techtrends
  namespace: sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techtrends-py-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: python-helloworld
    spec:
      containers:
      - image: docker2dk/techtrends:latest
        imagePullPolicy: IfNotPresent
        name: techtrends-app
        ports: 
        - containerPort: 3111
        resources:
          requests:
            cpu: 250m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 128Mi         
        livenessProbe:
		 httpGet:
		   path: /healthz
		   port: 3111
	   readinessProbe:
	      path: /healthz 
	      port: 3111
